safe        : true
lsi         : false
pygments    : true
timezone    : Europe/Athens

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]